{
 "title": "Native Performance Data of Hetzner Servers",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "vserver",
    "label": "VServer",
    "query": "label_values(hetzner_server_info,hetzner_vserver_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Network Packet Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hetzner_server_net_packet_per_second_read{hetzner_vserver_name=\"$vserver\"}",
     "legendFormat": "{{ hetzner_vserver_name }} RX pps"
    },
    {
     "expr": "hetzner_server_net_packet_per_second_write{hetzner_vserver_name=\"$vserver\"}",
     "legendFormat": "{{ hetzner_vserver_name }} TX pps"
    }
   ]
  },
  {
   "title": "Disk Throughput",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hetzner_server_disk_bandwidth_read{hetzner_vserver_name=\"$vserver\"}",
     "legendFormat": "{{ hetzner_vserver_name }} Read bps"
    },
    {
     "expr": "hetzner_server_disk_bandwidth_write{hetzner_vserver_name=\"$vserver\"}",
     "legendFormat": "{{ hetzner_vserver_name }} Write bps"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hetzner_server_cpu_load{hetzner_vserver_name=\"$vserver\"}",
     "legendFormat": "{{ hetzner_vserver_name }} CPU usage %"
    }
   ]
  },
  {
   "title": "Disk IO per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hetzner_server_disk_iops_read{hetzner_vserver_name=\"$vserver\"}",
     "legendFormat": "{{ hetzner_vserver_name }} Read iops"
    },
    {
     "expr": "hetzner_server_disk_iops_write{hetzner_vserver_name=\"$vserver\"}",
     "legendFormat": "{{ hetzner_vserver_name }} Write iops"
    }
   ]
  },
  {
   "title": "Network Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "bits", "label": "- out / + in" }
   ],
   "targets": [
    {
     "expr": "hetzner_server_net_bandwidth_in{hetzner_vserver_name=\"$vserver\"}",
     "legendFormat": "{{ hetzner_vserver_name }} in (download)"
    },
    {
     "expr": "hetzner_server_net_bandwidth_out{hetzner_vserver_name=\"$vserver\"}",
     "legendFormat": "{{ hetzner_vserver_name }} out (upload)"
    }
   ]
  }
 ]
}