{
 "title": "Hetzner Servers",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "loadbalancer",
    "label": "Load Balancer",
    "query": "label_values(hetzner_load_balancer_info,hetzner_load_balancer_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Open Connections",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hetzner_load_balancer_open_connections{hetzner_load_balancer_name=\"$loadbalancer\"}",
     "legendFormat": "{{ hetzner_load_balancer_name }}"
    }
   ]
  },
  {
   "title": "Connections per Second",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "hetzner_load_balancer_connections_per_second{hetzner_load_balancer_name=\"$loadbalancer\"}",
     "legendFormat": "{{ hetzner_load_balancer_name }} cps"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "bits", "label": "- out / + in" }
   ],
   "targets": [
    {
     "expr": "hetzner_load_balancer_bandwidth_in{hetzner_load_balancer_name=\"$loadbalancer\"}",
     "legendFormat": "{{ hetzner_load_balancer_name }}in"
    },
    {
     "expr": "hetzner_load_balancer_bandwidth_out{hetzner_load_balancer_name=\"$loadbalancer\"}",
     "legendFormat": "{{ hetzner_load_balancer_name }}out"
    }
   ]
  }
 ]
}